### ISSUE TITLE
Drag-Mock stopped working...

### ISSUE THREAD

**Issue by alek75** [andywer/drag-mock#11]
...since yesterday - 21.02.2017
I am using webdriverio but we are usingt this way  - http://webdriver.io/api/protocol/execute.html.

It worked untill yesterday.

The error i have is: 
Uncaught TypeError: dragMock.dragStart(...).dragEnter is not a function
at HTMLScriptElement.dragMockScript.onload (<anonymous>:365:22)
dragMockScript.onload @ VM250:365
app-bundle-e54693724e.js:5 

My code is:
  browser.execute(function () {
            var dragMockScript = document.createElement('script');
            var dragTarget = document.querySelector('#shortcuts-wrapper button:nth-child(1)');
            var dragOver = document.querySelector('#shortcuts-wrapper button:nth-child(2)');
            var dropTarget = document.querySelector('#shortcuts-wrapper button:nth-child(3)');

            dragMockScript.onload = function () {
                var dm = dragMock.dragStart(dragTarget)
                    .dragEnter(dragOver)
                    .dragOver(dragOver)
                    .dragLeave(dragOver)
                    .delay(500)
                    .drop(dropTarget);
            };

            dragMockScript.setAttribute('src', 'http://andywer.github.io/drag-mock/drag-mock.min.js');
            document.head.appendChild(dragMockScript);
        });

**Comment by andywer** [comment]
Hey @alek75! Sorry to hear that.

I released 1.4.0 yesterday. Only changes included cover this PR: #10
Not sure what could have broken it...

@shkaper Any idea?

**Comment by andywer** [comment]
Btw, you are not even using the [webdriver integration](https://github.com/andywer/drag-mock#webdriverio-integration)? Then nothing should have changed for you at all 🤔

Could you please state what version range you specified in your `package.json` and which one is actually installed in `node_modules/`?

**Comment by alek75** [comment]
Yes , i am not using it... i did not manage to make it work... In fact i am using the same way for other parts of the app and there are no problems. There were no PR merged to the  app at this time...

 "chai": "^3.5.0",
    "cucumber": "^1.3.1",
    "drag-mock": "^1.4.0",
    "wdio-browserstack-service": "^0.1.4",
    "wdio-cucumber-framework": "^0.2.15",
    "wdio-dot-reporter": "0.0.7",
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-selenium-standalone-service": "0.0.8",
    "wdio-spec-reporter": "0.0.5",
    "webdriverio": "^4.6.2"

**Comment by andywer** [comment]
`"drag-mock": "^1.4.0"`? So you just `npm i --save-dev` it...

Which version did you use before (the one that worked for you)?

**Comment by alek75** [comment]
We've found that yesterday sortable js, which we are using for this components was updated too.... I guess what happened is funny coincidence, cause I've updated drag-mock yesterday also(if this is the reason). I did a revert for drag-mock but still not working

**Comment by andywer** [comment]
That's strange, but I am a bit relieved.

How about that: I close the issue for now and you feel free to re-open it if it turns out that drag-mock behaved weirdly after all 😉

**Comment by alek75** [comment]
Yeap, I'll write if something special pops up

**Comment by shkaper** [comment]
Yep, it doesn't look like WebdriverBridge has anything to do with that. In fact, it shouldn't work at all for webdriverio 3+ the way it is now. (probably worth mentioning in README or something)

**Comment by andywer** [comment]
Added a line to the README to at least warn users: https://github.com/andywer/drag-mock#webdriverio-integration
